# ROOT NODE PARAMETERS
root_go2:
  ros__parameters:
    print_imu_info: false
    print_motor_info: false
    lowstate_topic_name: "/lowstate"
    odom_topic_name: "/sportmodestate"
    base_link_name: "base"
    n_motors: 12
    n_gripper_motors: 0
    joint_names:
      - "FR_hip_joint"
      - "FR_thigh_joint"
      - "FR_calf_joint"
      - "FL_hip_joint"
      - "FL_thigh_joint"
      - "FL_calf_joint"
      - "RR_hip_joint"
      - "RR_thigh_joint"
      - "RR_calf_joint"
      - "RL_hip_joint"
      - "RL_thigh_joint"
      - "RL_calf_joint"

# SIM NODE PARAMETERS
sim_go2:
  ros__parameters:
    robot_name: "go2"
    lowstate_topic_name: "/lowstate"
    lowcmd_topic_name: "/lowcmd"
    odom_topic_name: "/sportmodestate"
    xml_filename: "go2/go2.xml"
    base_link_name: "base"
    sole_link_name: "RR_point"
    sim_dt_ms: 1
    n_motors: 12
    n_gripper_motors: 0
    q_init:
      - 0.005
      - 0.72
      - -1.4
      - -0.005
      - 0.72
      - -1.4
      - -0.005
      - 0.72
      - -1.4
      - 0.005
      - 0.72
      - -1.4
